######################################################################
# Automatically generated by qmake (3.1) Tue Feb 26 14:10:49 2019
######################################################################

TEMPLATE = subdirs
SUBDIRS = utilities mainswitch sconfig audioswitch
 
