#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','/','h','o','m','e','/','y','a',
        'n','g','m','e','n','g','y','u','/','i','p','5','0','0','0','_','w','e',
        'b','/','c','r','o','s','s','t','o','o','l','/','g','c','c','-','3','.',
        '4','.','2','-','g','l','i','b','c','-','2','.','3','.','3','/','a','r',
        'm','-','a','s','p','e','e','d','-','l','i','n','u','x','-','g','n','u',
        '/','b','i','n','/','a','r','m','-','a','s','p','e','e','d','-','l','i',
        'n','u','x','-','g','n','u','-','g','c','c',' ','-','I','.',' ','-','I',
        '.','.',' ','-','I','.','.','/','i','n','c','l','u','d','e',' ',' ','-',
        'f','P','I','C',' ','-','D','O','P','E','N','S','S','L','_','P','I','C',
        ' ','-','D','Z','L','I','B','_','S','H','A','R','E','D',' ','-','D','Z',
        'L','I','B',' ','-','D','O','P','E','N','S','S','L','_','T','H','R','E',
        'A','D','S',' ','-','D','_','R','E','E','N','T','R','A','N','T',' ','-',
        'D','D','S','O','_','D','L','F','C','N',' ','-','D','H','A','V','E','_',
        'D','L','F','C','N','_','H',' ','-','I','/','h','o','m','e','/','y','a',
        'n','g','m','e','n','g','y','u','/','i','p','5','0','0','0','_','w','e',
        'b','/','A','3','0','-','K','r','a','m','e','/','p','r','e','f','i','x',
        '/','i','n','c','l','u','d','e',' ','-','O','3',' ','-','W','a','l','l','\0'
    };
    #define PLATFORM "platform: linux-armv4"
    #define DATE "built on: Fri Jun 18 09:55:24 2021"
#endif
