#
# Makefile for the ASPEED framebuffer device driver
#

obj-$(CONFIG_AST1500_DIGITAL_SOURCE) += cat6613.o
obj-$(CONFIG_AST1500_DIGITAL_SINK) += cat6613.o

cat6613-objs := IO.o cat6613_main.o cat6613_sys.o cat6613_drv.o